language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-ordering
  - pip install coveralls
  - python setup.py install
script:
  - python3 -m pytest --cov tinyscript tests
after_success:
  - coveralls
