language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install coveralls
  - pip install cairocffi>=1.0.0
  - python setup.py install
script:
  - nosetests -v --with-coverage --cover-tests --cover-package tinyscript tests
after_success:
  - coveralls
