language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-ordering
  - pip install coveralls
  - python setup.py install
script:
  - py.test --cov=tinyscript
after_success:
  - coveralls
