site_name: "Tinyscript - A library for quickly prototyping CLI Python-based tools"
repo_url: https://github.com/dhondta/tinyscript
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: index.md
  - Setup: setup.md
  - Internals: internals.md
  - Features: features.md
  - Usage: usage.md
  - Examples:
    - 'Simple script': examples/simple-script.md
    - 'Simple tool': examples/simple-tool.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
